default_config:

logger:
  default: warning
  logs:
    custom_components.denon_avr_net.sensor: debug
    custom_components.denon_avr_net.switch: debug
    custom_components.denon_avr_net.denon_tcp_client: debug
sensor:
  - platform: denon_avr_net
    host: '192.168.1.34'
switch:
  - platform: denon_avr_net
    name: Test Porch Alexa
    host: '192.168.1.34'
    zone: 3
    source: CD
  - platform: denon_avr_net
    name: Test Porch Projector
    host: '192.168.1.34'
    zone: 3
    source: AUX1