default_config:

logger:
  default: warning
  logs:
    custom_components.denon_avr_net: debug
    #custom_components.denon_avr_net.sensor: debug
    #custom_components.denon_avr_net.switch: debug
    #custom_components.denon_avr_net.denon_tcp_client: debug

denon_avr_net:
  - host: '192.168.1.34'

switch:
  - platform: denon_avr_net
    name: 'Test Denon Net'
    host: '192.168.1.34'
    sources:
      - name: Test Porch Alexa
        zone: 3
        source: CD
      - name: Test Porch Projector
        zone: 3
        source: AUX1
light:
  - platform: denon_avr_net
    name: 'Test Denon Net'
    host: '192.168.1.34'
    lights:
      - name: Test Porch Speakers
        on_command: Z3ON
        off_command: Z3OFF
        level_prefix: Z3
        min: 0
        max: 99