version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    #network_mode: host
    volumes:
      - ./configuration.yaml:/config/configuration.yaml
      - ./config:/config
      - ../:/config/custom_components/denon_avr_net
    environment:
      - TZ=America/New_York
    restart: always
    privileged: true
    ports:
      - "8123:8123"